[package]
name = "sdvdllg-game"
version = "0.1.0"
edition = "2021"
authors = ["Kenedy Nopriansyah", "kenedinovriansyah@gmail.com"]

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
bevy = "0.15.3"
bevy_kira_audio = "0.22.0"
rand = "0.9.0"
